version: "3.7"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      SQLITE_FILE: "/data/clash.db"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - "$PWD/data:/data"
